name: Push to Repository and Deploy to Vercel

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Commit and Push changes
        run: |
          git config user.name "deliondane"
          git config user.email "hynnk0@gmail.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Project Update"
            git push origin develop
          else
            echo "No changes to commit"
          fi
        env:
          STARBUCKS_GITHUB_KEY: ${{ secrets.STARBUCKS_GITHUB_KEY }}

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
