name: Push to Repository and Deploy to Vercel

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Commit and Push changes
        run: |
          git config user.name "deliondane"
          git config user.email "hynnk0@gmail.com" 
          git add .
          git commit -m "Project Update"
          git push origin develop
        env:
          STARBUCKS_GITHUB_KEY: ${{ secrets.STARBUCKS_GITHUB_KEY }}

      # 6. Vercel에 배포
      - name: Deploy to Vercel
        run: npx vercel —prod
        env:
          STARBUCKS_VERCEL_TOKEN: ${{ secrets.STARBUCKS_VERCEL_TOKEN }}
